language: ruby
rvm:
- 1.9.3
env:
- CHEF_VERSION=10.28.2
- CHEF_VERSION=11.6.2
before_script:
- chef-client --version
notifications:
  hipchat:
    rooms:
      secure: Q63RU8BnNe9l6vfiCTl6ENtk1CFt+bRGxN+CuLvj9huR22sjOv2ALI6Jfqa+KFNPrfQ+4EjSJfq7es6xpIZLxNK2XjYA2vlI+OVmktGO08nfClWyWgmdinObumJPwEB+eU4KhvScFYSVSd4Cv4zS30J/9x8iSAis4zwcIjsKdKI=
